language: python
dist: xenial
python:
  - '3.7'
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - python -m unittest
env:
  global:
    - TEST_FILES_LOCATION=test/test_files
deploy:
  provider: pypi
  user: naorlivne
  password:
    secure: rhA0/8wfzm3RAP8QGQLChln2pySpaRm4b/TmwXLfpBbS03+GLDn1I22AOGnIl5ai9Lv0r1uyhcZU2cli4Q6XJ6GM2tNHQEUwehfuxQvlqTnrcAvrhPSXOikyTy2ACCaNMrt/1lzXQGuAVev3BowYG+zrkbu2qw1x65IenNzp3XbarQi7Xwq/fMyT8ZaNExeqQWvOQby+U2lKaEoAyMZz7cVi2wIWsJsbfC/9s13isqN+Y4WhgcjSj6XpNksAYPNTQmhrwVBapO1Tq3maKkxmlYdo62IeBFHgTQFzjHIWJolfVWEdL/xAffki1YG5gZyVFrgJ6n86v+Eq4vlkkOXj7wVQp/3b51lE1O577j0ZwYly99+/FPItgA4hZqMBY12HR8NlfamjaN4rzH1CQV1u0az2j4/7abMFP97+Ud7bacIzYQQsW2pgGH00clQDHBg2qjs0MJrumeYW63+++GaM00fjM4DkkkOFtH0tlsW19eMvVvrF5Vcb2Y/0J9em/IFy82FisvFO4VXJDiueKJ1iVxHuQuWkIs3LHZjo4KJW1nWFWbJuhJLHwuI1WS6G1TfZN+/41tQ9yO9g3kj4tyyjhwjdjY0Evp7031g44m/pBzZi4TXiD56Y5be7mwEZli4mQLtuK8LVAzR8oqGqM3P5r000tffBX3UMuSUC/TTcMjo=
  distributions: sdist bdist_wheel
  skip_existing: true
