language: python
dist: xenial
python:
- '3.7'
services:
- docker
install:
- pip install -r requirements.txt
script:
- python -m unittest
env:
  global:
  - TEST_FILES_LOCATION=test/test_files
deploy:
  provider: pypi
  user: naorlivne
  password:
    secure: U5DeiOR6jai3MwZzcfHmMHtkep8xaiqYABTuBgDizcqxchnrLuUDQny1tnRhPqWE3VT1oRfbifgaccXUpVKa0GaGKQN0jvh4eY6A3A4EwbhWmRXO8pAyzM8oJ3Ri/9ozVBEBji/BSzG70wRk8gBtpIdTlfyXsX0oGG66ypTGYJCdwYohqMqtU9kM6MitRfesErQ5PibkiULzRUy04ayGO12e4Jd1YRPMcbBkwsYO3pJs7yzBjxKpvSqdFPBBwmzSHItFKj+FRcW5Ou7/a5qi0cKgRyr7Hri5/3odRk36C4WPCvZuPpDv/ou3FqGlYsEBs//DrIDmF1ARM3E5yAKYdOXIcgO5MvZV0Y8hsqaigHnILZmslL4JEBM5j9toDxGTNXr4D0XyvWv70q3Pa/SHhhH9ODDijOGzyGxtXLYE+8/X9VpCSekrZdpUvo3W/2LrwLQSdtzj6jz1FKukWd0CQscEgKUlET8KAQ1mEQ1W45g3h+yGN4wAQL3ynOylPeujMc1AXOarl4egdGxcd7E5gZnxa5Di8ZeohXADqBYOIO/pMLziMbAzvTyFBeCyWuMFL28PZvamcM0sIjUBITrtsdc9wdnrd+Um0fQMFWTFu5/aCSUmP52hTayYIpQmVFHp6vc0KxtUK3WJK2DlyE6C3RApJIeqzqLjXzoU2s6nZK0=
  distributions: sdist bdist_wheel
  skip_existing: true
