language: python
dist: xenial
python:
- '3.7'
services:
- docker
install:
- pip install -r requirements.txt
script:
- python -m unittest
env:
  global:
  - TEST_FILES_LOCATION=test/test_files
deploy:
  provider: pypi
  user: naorlivne
  password:
    secure: sCB+x1Q2GABLlpNPUOJgV6cJSyYxrrRjcLREEDau6ZISegKNiWMbLsUHgXHX7TkGAc3bH22ZQFk/mVtZcdKUwZPPSLuAQz0JjPbbymCt3BMDAZDIhR1tOJtd/yGCQnHniHpurRZyIbXVBmJPU+65qsxXDfg/XrQpyq81UUnDT13pgC4zvg/mZtVjZIVBv3T/Ad9TmrDCfXCZQWvBCcBC7jx20QN9mejeAiPPKU/nBybbsQ/KkuoGjRvl4eEzNVNI8vQjw66gQJ4RDcyug2EqN8+hFERZMn0MmxpsVFxM0EUDYLTZ5L5fqP2lx5/+mFu9kbd4FyQ8nHMcn0LIg/VD4JNl7VHGzKcMOwjwxYvn0+aJ0PIwTxEm8XajwyRbh5fjxubHePmQyCIPOebvnUJAII4DrpE00n4m6jSjHKiG+2sbAOAfrXPrR9kGVihdfDorLW/o6sLuHNF0l5vUQ9x0fkm0VEzmuLh3WKnKf/xVEHV5v0m6x1fvP89+zbT+2MB4YPBZ+6n4FkeDnOE549o3EdWR/+gvi62fBS6GvAXqIaqy4oFo7WHOErB0/QEn1BvZhF0WSXSSLNdUJb/Mn4rY4dbpe5K/HWGgwCw81RyCQpBQWMajx5i+c25vwSyGWtzF53HJSUYVBwkob00NnOZz64+s2DksJilKrFQRQWNQJ5Q=
  distributions: sdist bdist_wheel
  skip_existing: true
