language: python
dist: xenial
python:
- '3.7'
services:
- docker
install:
- pip install -r requirements.txt
script:
- python -m unittest
env:
  global:
  - TEST_FILES_LOCATION=test/test_files
deploy:
  provider: pypi
  user: naorlivne
  password:
    secure: CgHadsUPUcYTSzvpe0/R++wKxopiCk/VeuXlpLOM9shUSDYpKJKQZ0Bcg0ffQX2O1f+sPHlgQzx3IWZ+8GbzNzcktDcVuwz3mVQM0iApgr9J8LyEwBGv2ZMbR1NxZ6qlatdxqVTRUZ5ULgcvGHZB0TnxjSY0sW98e4kEPzrjnW2TeDeS9brAT1TKIl3HjRKPLpj6FW7SsPqXvQTkCXK78Ohfn3OTKXYGSK9pCmKI9EA+DZY8fK5LyjUxyq5JpjkoJB02is90kn7wb02CyGOoGWnvy4OC2mcaQAKWG3j40+pFBBSu3A4FT2oU8A5mDNVfvJLnuctAgZdBbq4y5SI7SSZgOAOpqP/4BNdd/aVr2nTzxMpswn1AbBs+emeWVMq7dUhk0husK0sDHdXIQRAA/CrQSPPsO5bDOkUeE058er+hLmhTC/VPxCuxgqourTX6wY5KtopcZwlufqNkLac+g80t6eIIlFyb8KK4+zITyHoJni+ACC7nsTsbx1MaTUuxHbqGbta6udRdlORd5yF9X+wenxiuR0zfHrw5SN1UzllvjiFbLiuuGkwf1WDMN0tYt+3nWqhipPNjluaXNk5WY2ggA8bAptyh1r/JDdgSU+hfqSe6wD2e/fx4KWWB7a4vSD3MnrcDXG/glcPvHYKjrPay9FxRns5JebTFBmHnKYM=
  distributions: sdist bdist_wheel
  skip_existing: true
