language: python
dist: xenial
python:
  - '3.7'
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover
deploy:
  provider: pypi
  user: naorlivne
  password:
    secure: AdTjJH6xfLUmTUlE+0e781QseC3WFdhNbXe5pgRndZVfLPOivpzSjR4kCzREW+ONKt8HDqQCemIXbd0tjulm1p81KuVPttv88iyXGCB9+UvBrg+Jl1rsWMY+lrqgfCpb8EfQxE0Yud8WYnBIGMYRFsGC9d1Cz80UhPd4NyKtlfbmv34p8ScPvlDfigmiFDxlJqmdFcmZ1o+RHnMv6IZr8QOLSQojDwNyMzgmCceJX0EqRRGGECCgJXuAJ0/0STk06ebfhzL+UZSbWGYOQWoUZgBKpZVewjwcF3QovQTf1d8rgMVvqMrP4bR4MQKmHvNoj0VpChaXtbkXNRGXWUTlfCPOcK325Gvyb3Sk1P0M0xVRN6T+yrkR+mvEynENuHCJRaXvLPS6a2SJWo5rCJOKZJNQazNGwgZ8CMAAfrhmDGvAVh4rguslAQ8AoAMyy7bC9GCV2ChPw7xso1QNCfiOcKre21M7bLpb2tuic1L0J4f45SfgiKhQps2lqPoXOdYwhhK64/05VRweE8YNQ5o8sPbnJu/G81gKzjDkp+z+Aizj7YrRaaA1gCkzKp5lxxreVDRfX5xQLf7k5TFeFgRxMgbTEavMkGG7mfI6CEEiROyHmM9J0ARM3WaU1hIRWvqDJi3UFc8ZOsHaAeDGyENmOp7VGYbVvjMT+VbhuQzARvg=
  distributions: sdist bdist_wheel
  skip_existing: true
