language: python
dist: xenial
python:
- '3.5'
- '3.6'
- '3.7'
services:
- docker
install:
- pip install -r requirements.txt
- pip install codecov
script:
- coverage run -m unittest
env:
  global:
  - TEST_FILES_LOCATION=test/test_files
  - GITHUB_USER=naorlivne
  - GITHUB_USER_EMAIL=naorlivne@gmail.com
  - GITHUB_PROJECT=parse_it
  - secure: HLVj8BF0BeCZ++eofKvYU5l9+cTAhB3WZUHkbbUc4ILlydWH8qdGisw6YgWOt+EgYfMjRm5mJ+PKiMqJP/4RGsj7U5kbui4Nybp/ySwXCnT/QF2bgGNQ7DWYmzWIJ7YR8IsSy/9lLT/h9GJtxVERzQX2TqagxnT3nUjErzozIoHoZBEAnInsgyV1ylgEhNR4SvlOgPdnFxpu9DAobvtfd8kDFseIx0IBoHVi2iPCqFHnDmjU/39n61PITfUoiVK1tAUslvn5Qm/4jYGWzuUd2UG8uB15tL62QlGMH6aEOQtBPUy07fs1rJOBr9IK5JQFNk1+v1wAXTKv9z06RJGqr1e5ug1FOvaSboQ3bjpz0O+RRjAWeCcUzzuXwutHgCGmDjzH1bIXj5XF3ajyzk6SEUgqUMmW5v6tL+mheMt264pYvrpYuhE4ykyQO3Zxv7A8F0VlehluTQ9XmnOmpvVbW6Z2n7hHWxADqmt1EpWaPQ0ZulrIHmJhhesC6zI7w/9tqjzlJ6GyOAW/mq+NJrFeAjxShozJCankJJFfETB529zHCPYfsCNABjY9NQAw5d+cep2zCc+W9gE1NksFa44fdfbHshQrj+Ue2eccw7qFxeOHsPyhgsY62fiQouDyGB5p0Phif/I6s7UZOp/kKsA58RuRlwKlmqTy/oZsVsFXHhc=
deploy:
  provider: pypi
  user: naorlivne
  password:
    secure: YSCB0Tbh/02MiPZNcUK/DTdjqTqwrOoXpr5VoPF7SVHm0H1+5B50TJGwFVebk2q+sdwN31JfUwPJ6ZpmVU7pooHoWYd2fkxq6xWoN0pZeC/UtJ0dHDNpR23CLvTte2lTz5vil90Vf63UxBEovq5YY9xl1wn3AAVTZX5VuraBroETZh7BFayN4S7aWKelytPQi4btL1ooNdZTq++DZ6TCWYnbQf2vvysSarOI/w2ZpVIEAWNEd40Ocp2GoXQN6LB1KrEw/eww1816sLjpiSU/4u/UyQWcHORIE42WdBM/Ze2We1jf2uZsQLWTPO1E5xE4l7jomiNp1EBTmpeUYRjUEOgS7vPEl8UvVNasEDqRZMBhGCTQKHnR+jmjFxCRVukZ/p/R2DpkbSwqVWhOpishVPS0/wSBYEoOMKOxBAwpJM7KNCgHmnG+M5lW8y7G0BDixqQa8l4rXKjskTgvin4kY2h7zWMbWjRKSdnVsGTkVWWquYSLWuZkfsSxf2Kz1qdDOiKgrzpLaLz07OgPsgaGpSVX4BO1aGik7w0iKG/jmRkYwlMuaIMfITYzWUqnZcXOaQnGFypuVsLOnEcFORz66DiCM4gMavg0WfmW+SHgYG2mk6ASQ0BLdkddu0le6DYjxIgMc5Iscir72GxjWCMWQo1ESFVh0vvrsQtXYF5bKzg=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    python: '3.7'
after_deploy:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config --local user.name "${GITHUB_USER}"
- git config --local user.email "${GITHUB_USER_EMAIL}"
- git commit -m '[skip travis] build $TRAVIS_BUILD_NUMBER pushed - new parse_it version released'
- git tag $(python setup.py --version)
- git push origin $(python setup.py --version)
- docker run -e GITHUB_USER=${GITHUB_USER} -e GITHUB_PROJECT=${GITHUB_PROJECT} -e CHANGELOG_GITHUB_TOKEN=${GH_TOKEN} -v `pwd`:/output naorlivne/github-changelog-generator-dockerized
- git add CHANGELOG.md
- git commit -m '[skip travis] build ${TRAVIS_BUILD_NUMBER} pushed - new version changelog'
- git push
after_success:
- codecov
