language: python
dist: xenial
python:
- '3.7'
services:
- docker
install:
- pip install -r requirements.txt
script:
- python -m unittest
env:
  global:
  - TEST_FILES_LOCATION=test/test_files
  - secure: NCu2Y1dz5SwWLfZRKrrh7QHJTQZRFEYxeIFQ8GE7zc0J4jgr3Kawy2I/HLt25Q+O4M0Tt+gkmyhY0F9fKY2xEhf1ePLzjl/JU+Mu0HDJBf5qnmv7S7ht7+NF7m3koXfnpe3cpvs9NrWYJD7GpIBZ4zOkovv6FvttFczkJzR92DphLImqYXtxV/UmEthQ6eLsLwfIkUGzr2gd2ItrpaUFsfiJspKjXtrisDDWTOKrkAWk5yHjH2/NFqCckDbmNnps29ebBJoE9qbGqDOvu+OKj66kK/WWHNxM1pczcEH0OixadnQnaNvjj0tsF3n6f8umc0yCfH8bbmCwBvP9JEFYp9V8LZevd+APRYQt0QGgFGLI0j3H72ttSjpfrKQo6yI0DvtxhVO7t6GVvU8xKQNhQAJHyrVbGGyUqxLvRgjsc91o0Lp1tkQcD3pr0Bg0NkLMmYtapaA4qGesew4Mw/o8z4A2gKqNUaIJoBA/L4nKJvagSiOkV7xQHXA5QPXaoQ0MwJDsYPkaixXUbbbMtDlQw4PUZRA08g9jhDT6jHG+8YJkFO3fB4qoHe7uVK6hW+xHytvzKKr/Z74a45+sxAN5xOBoN170AKsQ+qf6KBUfEBgDP4C0mOOU5NHKXbL4S0xwSqPOnyU652E56U2lyKETLaTIg4JcV0DP9nz+u9NylzY=
deploy:
  provider: pypi
  user: naorlivne
  password:
    secure: YSCB0Tbh/02MiPZNcUK/DTdjqTqwrOoXpr5VoPF7SVHm0H1+5B50TJGwFVebk2q+sdwN31JfUwPJ6ZpmVU7pooHoWYd2fkxq6xWoN0pZeC/UtJ0dHDNpR23CLvTte2lTz5vil90Vf63UxBEovq5YY9xl1wn3AAVTZX5VuraBroETZh7BFayN4S7aWKelytPQi4btL1ooNdZTq++DZ6TCWYnbQf2vvysSarOI/w2ZpVIEAWNEd40Ocp2GoXQN6LB1KrEw/eww1816sLjpiSU/4u/UyQWcHORIE42WdBM/Ze2We1jf2uZsQLWTPO1E5xE4l7jomiNp1EBTmpeUYRjUEOgS7vPEl8UvVNasEDqRZMBhGCTQKHnR+jmjFxCRVukZ/p/R2DpkbSwqVWhOpishVPS0/wSBYEoOMKOxBAwpJM7KNCgHmnG+M5lW8y7G0BDixqQa8l4rXKjskTgvin4kY2h7zWMbWjRKSdnVsGTkVWWquYSLWuZkfsSxf2Kz1qdDOiKgrzpLaLz07OgPsgaGpSVX4BO1aGik7w0iKG/jmRkYwlMuaIMfITYzWUqnZcXOaQnGFypuVsLOnEcFORz66DiCM4gMavg0WfmW+SHgYG2mk6ASQ0BLdkddu0le6DYjxIgMc5Iscir72GxjWCMWQo1ESFVh0vvrsQtXYF5bKzg=
  distributions: sdist bdist_wheel
  skip_existing: true
